name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: gradle build

      - name: Start application
        run: java -jar app-replan-delivery.jar &   

      - name: Wait for application to start
        run: sleep 5  

      - name: Run tests
        run: gradle test